### ISSUE TITLE
Web hosting

### ISSUE THREAD

**Issue by finnbear** [fixmyrights/discord-bot#12]
Please discuss which option is best
- VPS
  - AWS EC2
  - Linode
  - Heroku
- FaaS
  - Heroku
  - AWS Lambda
- Random server
- Random computer in basement

However, as the differences between providers are not significant, I won't even look at this issue until all the code is done.

**Comment by ChadBailey** [comment]
Someone is offering free hosting on digital ocean. i'd be glad to lend some space on my server (linode) as well if needed. i don't think the host is overly important - but i do see uptime as a priority. for that reason my only veto is a random basement

**Comment by joaodforce** [comment]
We plan to build the bot to be very lightweight, in order to make it very easy on hosting.
We already have a VPS on Vultr that we plan to use for the short to medium term.

Also considering this will host the API KEY that will probably be bough by Louis, and also a bot Access KEY that willl have access to Louis's Rossmann server, the hosting should be secure, and held only by the stakeholders.

**Comment by ChadBailey** [comment]
i'm a bit confused on a few things here.

first, i do think that having someone figure out hosting and setting up a pipeline would be a great thing to get started now rather than parking the matter.

second, i did not realize there was a cost associated with an API key. i think it may be a good idea to set up a credentials store so that the api key is protected though, regardless of where it's held.

finally, i find it odd that you say hosting should only be done by the stakeholders. to say that would imply there is a group of stakeholders. i thought this was a collaborative open source project. i doubt that louis really cares where/how/who hosts it, so long as he doesn't have to think about it or manage it and just knows it will work

**Comment by finnbear** [comment]
I'm not interested in entering into the server/pipeline discussion just yet but as for the "stakeholders," you can interpret that as the people who provision the local/cloud hosting for the bot. There is no reason to have every contributor be a sysadmin. That said, the code is collaborative and open source. You are welcome to contribute. You can even host your own copy of the code.

**Comment by ChadBailey** [comment]
you've made yourself loud and clear, good luck with your project

**Comment by ghost** [comment]
@ChadBailey Thanks for bringing the point, very appreciated!

> first, i do think that having someone figure out hosting and setting up a pipeline would be a great thing to get started now rather than parking the matter.

You're absolutely right! I intend to setup the CI/CD pipeline ASAP but if you want to give us a hand with that, I'm all in!

> second, i did not realize there was a cost associated with an API key. i think it may be a good idea to set up a credentials store so that the api key is protected though, regardless of where it's held.

Using a secret manager or a vault for storing credentials is definitely an absolute must!

> finally, i find it odd that you say hosting should only be done by the stakeholders. to say that would imply there is a group of stakeholders. i thought this was a collaborative open source projec

There're always code-owners/maintainers in every open-source project out there that's inevitable.

Yes, this project is a community project and everyone that wants to be seriously involved can be a maintainer, you just have to ask.

However, we can't let _everyone_ access the production infrastructure that would be an absolute hell of a mess.

**Updated:**
Louis offered to pay for a VPS as well.

**Comment by finnbear** [comment]
Closed since we are hosting on a free GCP vm for now. Will reopen if we need to change provider.
